### ISSUE TITLE
How are these hosts found and added?

### ISSUE THREAD

**Issue by T145** [no-cmyk/Search-Engine-Spam-Blocklist#3]
I'm curious if these sources are pulled from other lists, built automatically by some web scanner, etc.

**Comment by no-cmyk** [comment]
I find them by searching for random combinations of words/concepts that can be found almost solely in these types of domains (e.g. "business inquiries" "hot sex"), or by noticing them in my daily searches. I then try to find recurring patterns either in the structure of the sentences, the words themselves or the hostnames, so I can narrow the search and find more.
A very useful tool I often use when searching for hostname patterns is whoisxmlapi.com.
