### ISSUE TITLE
Unblock aaoth.xyz

### ISSUE THREAD

**Issue by marek22k** [no-cmyk/Search-Engine-Spam-Blocklist#7]
Domain: `aaoth.xyz`

Hello,

aaoth.xyz is a part of [Yggdrasil network](https://yggdrasil-network.github.io/). It is listed as a public peer in [https://github.com/yggdrasil-network/public-peers/blob/master/europe/netherlands.md](https://github.com/yggdrasil-network/public-peers/blob/master/europe/netherlands.md). I visited aaoth.xyz and it does not seem to be spam, but a small personal homepage.

(I am not the operator of this node or domain, only a participant in the Yggdrasil network)

**Comment by no-cmyk** [comment]
Removed, thanks for the feedback.
